### ISSUE TITLE
feat: Submitter create a task per shot from the scene's MRQ

### ISSUE THREAD

**Issue by andymanaws** [aws-deadline/deadline-cloud-for-unreal-engine#57]
### Expected Behaviour

For each shot in the MRQ, a single task should be created, allowing parallel rendering.
(In an ideal world, we would also offer sub shot chunking as well, but this is trickier with stochastic problems).
I could no see a way around this?

### Current Behaviour

For the MRQ, only a single task is made.
It should make a task per shot ( as in Deadline 10's behaviour)

### Reproduction Steps

Create a multi shot setup in the MRQ ( Meerkat scene is great).
Submit the job - you only get a single task.

### Code Snippet

NA

**Comment by steve-fong** [comment]
This feature is crucial for us, as we handle large renders that require fast turnaround times.  Without it, the advantage of rendering with AWS dissolves.  Will buy beer for the first person who pushes out a fix.  :)

**Comment by jusiskin** [comment]
Hello @andymanaws! Thank you for your contribution. This is a great enhancement suggestion. We have added this to our backlog and will look into prioritizing it accordingly.

We will reach out here with any updates or questions.

**Comment by baxeaz** [comment]
Merged - https://github.com/aws-deadline/deadline-cloud-for-unreal-engine/pull/78
